version: '3.8'

services:
  fastapi:
    restart: always
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/src:/app/src
      - ./fastapi/src/logs:/app/src/logs
    depends_on:
      - mysql
    command: [
      "/usr/local/bin/wait-for-it",
      "mysql:3306", "--",
      "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"
      ]

  mysql:
    restart: unless-stopped
    build:
      context: ./mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log.cnf:/etc/mysql/conf.d/log.cnf:ro
      - ./mysql/logs:/var/log/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
      ]