services:
  fastapi:
    restart: always
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    volumes:
      - ./fastapi/src:/app/src
      - ./fastapi/ai_model:/app/ai_model  # 로컬 AI 모델 파일을 컨테이너에 마운트
    ports:
      - "8001:8001"
    environment:
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SEARCH_ENGINE_ID=${SEARCH_ENGINE_ID}
      - TREE_KEY=${TREE_KEY}
      - IP=${IP}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia